import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription, SheetFooter } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { ScrollArea } from "@/components/ui/scroll-area";
import { CheckCircle2, Circle, MapPin, Mail, Clock, ArrowRight, Sparkles, Brain, FileText } from "lucide-react";
import { motion } from "framer-motion";

interface TerritoryPlanProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function TerritoryPlan({ open, onOpenChange }: TerritoryPlanProps) {
  const planSteps = [
    {
      time: "09:00 AM",
      type: "visit",
      title: "Visit Dr. Sarah Smith",
      location: "Memorial Sloan Kettering",
      priority: "High",
      reasoning: "Switch risk detected. Competitor X gaining share in RCC.",
      action: "Review Phase 3 Survival Data",
      icon: MapPin,
      status: "pending"
    },
    {
      time: "11:30 AM",
      type: "email",
      title: "Outreach to Dr. James Wilson",
      location: "Digital / Remote",
      priority: "Medium",
      reasoning: "Low engagement with recent dosing update.",
      action: "Send 'Simplified Dosing' Draft",
      icon: Mail,
      status: "ready"
    },
    {
      time: "01:00 PM",
      type: "meeting",
      title: "Lunch: Dr. Emily Chen",
      location: "The Modern, NYC",
      priority: "High",
      reasoning: "Key Opinion Leader (KOL) development.",
      action: "Discuss Immunotherapy Symposium",
      icon: Clock,
      status: "confirmed"
    }
  ];

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent className="w-full sm:max-w-[540px] bg-[#F5F5F7] p-0 border-l border-black/5 shadow-2xl">
        <div className="flex flex-col h-full">
          {/* Header */}
          <div className="px-8 py-8 bg-white border-b border-black/5">
            <div className="flex items-center gap-3 mb-4">
              <div className="h-10 w-10 rounded-2xl bg-black flex items-center justify-center shadow-lg shadow-black/20">
                <Sparkles className="h-5 w-5 text-white" />
              </div>
              <div>
                <SheetTitle className="text-[24px] font-semibold tracking-tight text-[#1d1d1f]">Daily Orchestration</SheetTitle>
                <SheetDescription className="text-[14px] text-[#86868b] font-medium">Generated by Agent Copilot • Oct 24, 2025</SheetDescription>
              </div>
            </div>
            
            <div className="bg-[#F5F5F7] rounded-xl p-4 border border-black/5">
              <div className="flex items-start gap-3">
                <Brain className="h-4 w-4 text-[#1d1d1f] mt-1 shrink-0" />
                <p className="text-[14px] text-[#1d1d1f] leading-relaxed">
                  <span className="font-semibold">Agent Logic:</span> Analyzed 1,248 HCP profiles. Prioritized 3 interactions to maximize territory coverage and address immediate switch risks in North Manhattan.
                </p>
              </div>
            </div>
          </div>

          {/* Timeline */}
          <ScrollArea className="flex-1 px-8 py-8">
            <div className="space-y-8 relative">
              {/* Connecting Line */}
              <div className="absolute left-[19px] top-4 bottom-4 w-[2px] bg-gray-200" />

              {planSteps.map((step, i) => (
                <motion.div 
                  key={i}
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.1 }}
                  className="relative pl-12 group"
                >
                  {/* Timeline Node */}
                  <div className="absolute left-0 top-1 h-10 w-10 bg-white rounded-full border-2 border-[#F5F5F7] flex items-center justify-center z-10 shadow-sm group-hover:scale-110 transition-transform duration-300">
                    <step.icon className="h-4 w-4 text-[#1d1d1f]" />
                  </div>

                  <div className="bg-white rounded-[20px] p-5 shadow-[0_4px_20px_rgb(0,0,0,0.03)] border border-transparent hover:border-black/5 transition-all">
                    <div className="flex justify-between items-start mb-3">
                      <div className="flex items-center gap-2">
                        <Badge variant="secondary" className="bg-[#F5F5F7] text-[#1d1d1f] hover:bg-[#ebebeb] border-none rounded-full px-3 font-semibold text-[11px] uppercase tracking-wide">
                          {step.time}
                        </Badge>
                        <span className="text-[13px] text-[#86868b] font-medium capitalize">{step.type}</span>
                      </div>
                      {step.priority === 'High' && (
                        <Badge className="bg-red-50 text-red-600 hover:bg-red-100 border-none rounded-full px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-wide">
                          High Priority
                        </Badge>
                      )}
                    </div>

                    <h3 className="text-[17px] font-semibold text-[#1d1d1f] mb-1">{step.title}</h3>
                    <p className="text-[14px] text-[#86868b] mb-4 flex items-center gap-1.5">
                      <MapPin className="h-3.5 w-3.5" /> {step.location}
                    </p>

                    <div className="bg-[#F5F5F7]/50 rounded-xl p-3 mb-3">
                       <p className="text-[13px] text-[#1d1d1f]">
                         <span className="font-semibold text-[#86868b] text-[11px] uppercase tracking-wide block mb-1">Context</span>
                         {step.reasoning}
                       </p>
                    </div>

                    {step.status === 'ready' && (
                      <Button variant="outline" className="w-full rounded-xl h-10 border-dashed border-gray-300 text-[#1d1d1f] text-[13px] font-medium hover:bg-[#F5F5F7] hover:border-gray-400">
                        <FileText className="mr-2 h-3.5 w-3.5" /> Review Draft
                      </Button>
                    )}
                  </div>
                </motion.div>
              ))}
            </div>
          </ScrollArea>

          {/* Footer */}
          <div className="p-8 bg-white border-t border-black/5">
            <Button className="w-full h-12 rounded-full bg-[#1d1d1f] hover:bg-black text-white text-[15px] font-medium shadow-xl shadow-black/10 transition-all hover:scale-[1.02]">
              <CheckCircle2 className="mr-2 h-5 w-5" />
              Confirm & Sync to Calendar
            </Button>
          </div>
        </div>
      </SheetContent>
    </Sheet>
  );
}
